<a href="https://colab.research.google.com/github/MichaelYeung2004/deep-learning-with-pytorch/blob/main/ch2-1_making_sure_things_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.version.__version__

'2.6.0+cu124'

In [3]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
b = torch.ones(3,3)

In [5]:
a+b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [6]:
a = a.to('cuda') # 将张量a从CPU内存移动到GPU(CUDA设备)上
b = b.to('cuda')
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')