<a href="https://colab.research.google.com/github/MichaelYeung2004/deep-learning-with-pytorch/blob/main/ch3-1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
a = [1.0, 2.0, 1.0]
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points=torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points[0]

tensor([4., 1.])

In [14]:
points[0,1]

tensor(1.)

In [15]:
points[1:] #第1行之后的所有行，隐含所有列

tensor([[5., 3.],
        [2., 1.]])

In [16]:
points[1:, :] # 第1行之后的所有行，所有列

tensor([[5., 3.],
        [2., 1.]])

In [17]:
points[1:, 0] # 第1行之后的所有行，第1列

tensor([5., 2.])

In [18]:
points[None] # 添加一个维度

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage() # 查看张量的存储

/tmp/ipython-input-19-2387334797.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage() # 查看张量的存储


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [20]:
points_storage = points.storage() # 查看张量的存储
points_storage[0] # 查看张量存储中的第一个元素

4.0

In [21]:
points.storage()[1]

1.0

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset() # 查看张量存储中的偏移量

2

In [24]:
second_point.size(),second_point.shape # 查看张量的形状

(torch.Size([2]), torch.Size([2]))

In [25]:
points.size() # 查看张量的形状

torch.Size([3, 2])

In [26]:
another_point = points[1].clone() # 复制张量
another_point.storage_offset()

0

In [27]:
second_point = points[1]
second_point

tensor([5., 3.])

In [28]:
second_point.stride() # 每往后读取一个数，在内存中的间隔

(1,)

In [29]:
points.stride() # 每往后按行/列读取一个数，在内存中的间隔

(2, 1)

In [30]:
points_t = points.t() # 转置
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [31]:
id(points.storage()) == id(points_t.storage()) # 并不是克隆

False

In [32]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [33]:
points_t.stride()

(1, 2)

In [34]:
some_t = torch.ones(3, 4, 5)
some_t.stride()

(20, 5, 1)

In [35]:
transpose_t = some_t.transpose(0, 2)
transpose_t.shape

torch.Size([5, 4, 3])

In [36]:
transpose_t.stride()

(1, 5, 20)

In [37]:
points.is_contiguous() # 内存是否连续

True

In [38]:
points_t.is_contiguous()

False

In [39]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [40]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [41]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [42]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [43]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [44]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [45]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [46]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
print(points_64)
print(points_short)
print(points_64 * points_short)

tensor([0.2793, 0.4134, 0.0849, 0.1999, 0.5054], dtype=torch.float64)
tensor([0, 0, 0, 0, 0], dtype=torch.int16)
tensor([0., 0., 0., 0., 0.], dtype=torch.float64)


In [47]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [48]:
some_list = list(range(6))
print(some_list[:])
print(some_list[1:4])
print(some_list[1:])
print(some_list[:4])
print(some_list[:-1])
print(some_list[1:4:2])

[0, 1, 2, 3, 4, 5]
[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


In [49]:
points[1:]
points[1:, :]
points[1:, 0]
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [50]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [51]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
torch.save(points, 'ourpoints.t') # Save the tensor to a file in the current directory

In [53]:
with open('./ourpoints.t','wb') as f:
   torch.save(points, f)

In [54]:
points = torch.load('./ourpoints.t')

In [55]:
with open('./ourpoints.t','rb') as f:
   points = torch.load(f)

In [56]:
import h5py

f = h5py.File('./ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close

<bound method File.close of <HDF5 file "ourpoints.hdf5" (mode r+)>>

In [57]:
f = h5py.File('./ourpoints.hdf5', 'r')

In [58]:
dset = f['coords']
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [59]:
last_points = dset[:]
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [61]:
points=torch.tensor(dset[:])
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

torch.tensor():复制数据

torch.from_numpy():共享内存

In [62]:
points=torch.from_numpy(dset[:])
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [63]:
last_points = torch.from_numpy(dset[-2:])
f.close()